[project]
name = "devpulse-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anishvs14", email = "anish.sirdeshpande@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
devpulse-backend = "devpulse_backend:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
